### ISSUE TITLE
Can't install any version > 0.03 with cpan/cpanm

### ISSUE THREAD

**Issue by chocolateboy** [sukria/Test-TinyMocker#8]
```
$ cpanm Test::TinyMocker
Test::TinyMocker is up to date. (0.03)
```

The response from http://cpanmetadb.plackperl.org/v1.0/package/Test::TinyMocker is:

``` yaml

---
distfile: S/SU/SUKRIA/Test-TinyMocker-0.05.tar.gz
version: 0.03
```

\- which [it gets](https://github.com/miyagawa/cpanmetadb-perl/issues/2#issuecomment-9669622) from [CPAN](http://www.cpan.org/modules/02packages.details.txt.gz):

```
Test::TinyMocker                   0.03  S/SU/SUKRIA/Test-TinyMocker-0.05.tar.gz
```

I guess updating [this](https://github.com/sukria/Test-TinyMocker/blob/9b91be0b1f49632173c62986500ddbd0882ac625/lib/Test/TinyMocker.pm#L11) will fix it:

``` perl
$VERSION = '0.03';
```
